- date: 2020-11-23 10:17:17
- author: Jerry Su
- slug: tf.math
- title: tf.math
- category: 
- tags: Deep Learning, TensorFlow

- +, -, *, /

- **, pow, square

- sqrt

- //, %

- exp, log

- @, matmul

- linear layer

### element-wise
    
- +, -, *, /

### matrix-wise

- @, matmul

### dim-wise

- reduce_mean/max/min/sum

In [2]:
import tensorflow as tf

## 1. element-wise

In [6]:
a = tf.ones([2, 2])
b = tf.fill([2, 2], 2.)

In [9]:
a, b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>)

In [11]:
a + b, a - b, a * b, a / b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1., -1.],
        [-1., -1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.5, 0.5],
        [0.5, 0.5]], dtype=float32)>)

In [12]:
b // a, b % a

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [13]:
tf.math.log(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [14]:
tf.exp(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

In [15]:
tf.pow(b, 3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [17]:
b**3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [18]:
tf.sqrt(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

## 2. matrix-wise

- ( b, 2, 3 ) @ ( b, 3, 5 ) = ( b, 2, 5 ) ,  b is batch_size

In [19]:
a@b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [20]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [26]:
c = tf.ones([4, 2, 3])
d = tf.fill([4, 3, 5], 2.)
c, d

(<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
 array([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],
 
        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],
 
        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],
 
        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]], dtype=float32)>)

In [27]:
c@d

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

In [28]:
# with broadcasting
e = tf.ones([4, 2, 3])
f = tf.fill([3, 5], 2.)
e.shape, f.shape

(TensorShape([4, 2, 3]), TensorShape([3, 5]))

In [30]:
ff = tf.broadcast_to(f, [4, 3, 5])
ff.shape

TensorShape([4, 3, 5])

In [31]:
e@ff

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

## 3. dim-wise

In [ ]:
!pip install torch

     |██████▉                         | 165.9 MB 8.3 MB/s eta 0:01:147  |                                | 2.4 MB 567 kB/s eta 0:22:45     |▏                               | 4.6 MB 4.1 MB/s eta 0:03:09     |▍                               | 8.4 MB 4.1 MB/s eta 0:03:08     |▍                               | 9.6 MB 4.1 MB/s eta 0:03:08     |▌                               | 10.8 MB 7.2 MB/s eta 0:01:47     |▌                               | 11.3 MB 7.2 MB/s eta 0:01:46     |▋                               | 13.6 MB 7.2 MB/s eta 0:01:46     |▋                               | 14.6 MB 7.2 MB/s eta 0:01:46     |▊                               | 16.8 MB 7.2 MB/s eta 0:01:46     |▊                               | 18.1 MB 7.2 MB/s eta 0:01:46     |▉                               | 20.1 MB 7.2 MB/s eta 0:01:45     |█                               | 22.6 MB 12.7 MB/s eta 0:01:00     |█                               | 23.1 MB 12.7 MB/s eta 0:01:00     |█                               | 24.8 MB 12.