- date: 2021-02-07 12:17:17
- author: Jerry Su
- slug: pytorch-tensor-indexing
- title: Pytorch-tensor-indexing
- category: 
- tags: Deep Learning, Pytorch

In [1]:
import torch

## 一. 2维Tensor索引

In [11]:
trans_matrix = torch.randn(8, 8)
trans_matrix

tensor([[ 0.5018,  0.4398,  0.0640,  0.1166, -0.9359, -0.5330, -0.0846, -1.9441],
        [ 0.4020, -1.1602,  0.0970, -0.7664, -0.1459,  0.4404,  0.7028,  1.6285],
        [-0.1601,  0.2676,  0.6868,  0.5318, -0.3392, -0.1916, -0.7202,  1.6318],
        [ 0.7315,  1.5422, -0.1916, -0.1396,  0.7202,  0.7700,  2.5994,  1.5833],
        [-1.3667,  1.1020, -0.2463,  2.1035, -1.0413,  0.4249,  0.0398, -0.6893],
        [-0.5338,  1.1837,  1.1627,  0.4413,  0.2768, -0.5518, -0.7255,  0.4226],
        [ 1.1816,  1.5774, -1.3915,  1.2548,  0.3516,  0.6880,  0.8448,  0.0823],
        [-0.9731,  0.8838,  0.9227, -0.9670, -0.6315,  0.1609, -1.4294,  0.7157]])

In [12]:
index = torch.tensor([[6, 4, 2, 5, 5, 3, 4, 7, 0],
                      [6, 4, 2, 3, 4, 4, 7, 0, 0],
                      [6, 2, 5, 3, 4, 7, 0, 0, 0]])
index

tensor([[6, 4, 2, 5, 5, 3, 4, 7, 0],
        [6, 4, 2, 3, 4, 4, 7, 0, 0],
        [6, 2, 5, 3, 4, 7, 0, 0, 0]])

In [14]:
index = index.transpose(0, 1)
index

tensor([[6, 6, 6],
        [4, 4, 2],
        [2, 2, 5],
        [5, 3, 3],
        [5, 4, 4],
        [3, 4, 7],
        [4, 7, 0],
        [7, 0, 0],
        [0, 0, 0]])

In [15]:
index1= index[:-1]
index1

tensor([[6, 6, 6],
        [4, 4, 2],
        [2, 2, 5],
        [5, 3, 3],
        [5, 4, 4],
        [3, 4, 7],
        [4, 7, 0],
        [7, 0, 0]])

In [16]:
index2 = index[1:]
index2

tensor([[4, 4, 2],
        [2, 2, 5],
        [5, 3, 3],
        [5, 4, 4],
        [3, 4, 7],
        [4, 7, 0],
        [7, 0, 0],
        [0, 0, 0]])

In [17]:
trans_matrix[index1, index2]   # tensor 2维索引

tensor([[ 0.3516,  0.3516, -1.3915],
        [-0.2463, -0.2463, -0.1916],
        [-0.1916,  0.5318,  0.4413],
        [-0.5518,  0.7202,  0.7202],
        [ 0.4413, -1.0413, -0.6893],
        [ 0.7202, -0.6893, -0.9731],
        [-0.6893, -0.9731,  0.5018],
        [-0.9731,  0.5018,  0.5018]])

In [18]:
trans_matrix

tensor([[ 0.5018,  0.4398,  0.0640,  0.1166, -0.9359, -0.5330, -0.0846, -1.9441],
        [ 0.4020, -1.1602,  0.0970, -0.7664, -0.1459,  0.4404,  0.7028,  1.6285],
        [-0.1601,  0.2676,  0.6868,  0.5318, -0.3392, -0.1916, -0.7202,  1.6318],
        [ 0.7315,  1.5422, -0.1916, -0.1396,  0.7202,  0.7700,  2.5994,  1.5833],
        [-1.3667,  1.1020, -0.2463,  2.1035, -1.0413,  0.4249,  0.0398, -0.6893],
        [-0.5338,  1.1837,  1.1627,  0.4413,  0.2768, -0.5518, -0.7255,  0.4226],
        [ 1.1816,  1.5774, -1.3915,  1.2548,  0.3516,  0.6880,  0.8448,  0.0823],
        [-0.9731,  0.8838,  0.9227, -0.9670, -0.6315,  0.1609, -1.4294,  0.7157]])

## 二. 3维Tensor索引

In [44]:
logits = torch.randn(4, 3, 5)
logits = logits.transpose(0, 1)
logits

tensor([[[ 1.0069,  0.5182, -0.4227, -0.5194, -1.6969],
         [ 0.4987,  0.8371,  0.4351, -0.1743, -1.0407],
         [ 0.7765, -0.0659, -0.4499,  0.6877, -0.1851],
         [-0.5196,  1.6021, -0.8054, -1.1669, -0.3488]],

        [[ 0.1300, -1.0548,  0.2392, -1.2067,  0.3024],
         [-1.5936, -1.2103,  1.4773,  0.8156,  0.5295],
         [-0.4416, -0.5252, -0.9666, -0.1766, -0.4289],
         [ 0.7704, -0.7821,  0.2555, -0.9723, -0.3204]],

        [[-0.1897,  0.6734,  0.4039,  0.1909, -0.6221],
         [-1.8639, -2.5551, -1.8447, -0.2174, -0.1130],
         [ 1.5667,  2.4276, -1.8247, -0.2462,  0.0605],
         [-0.0302,  0.4692,  0.2567, -1.3758,  1.2917]]])

In [69]:
seq = torch.arange(4)
print(seq)
seq = seq.view(-1, 1)
seq

tensor([0, 1, 2, 3])


tensor([[0],
        [1],
        [2],
        [3]])

In [70]:
batch = torch.arange(3)
print(batch)
batch = batch.view(1, -1)
batch

tensor([0, 1, 2])


tensor([[0, 1, 2]])

In [71]:
index = torch.tensor([[4, 4, 2, 0],
                      [4, 4, 2, 2],
                      [4, 7, 0, 0]]).transpose(0, 1)
index

tensor([[4, 4, 4],
        [4, 4, 7],
        [2, 2, 0],
        [0, 2, 0]])

In [72]:
logits[seq, batch, index]

IndexError: index 3 is out of bounds for dimension 0 with size 3

In [52]:
logits

tensor([[[ 1.0069,  0.5182, -0.4227, -0.5194, -1.6969],
         [ 0.4987,  0.8371,  0.4351, -0.1743, -1.0407],
         [ 0.7765, -0.0659, -0.4499,  0.6877, -0.1851],
         [-0.5196,  1.6021, -0.8054, -1.1669, -0.3488]],

        [[ 0.1300, -1.0548,  0.2392, -1.2067,  0.3024],
         [-1.5936, -1.2103,  1.4773,  0.8156,  0.5295],
         [-0.4416, -0.5252, -0.9666, -0.1766, -0.4289],
         [ 0.7704, -0.7821,  0.2555, -0.9723, -0.3204]],

        [[-0.1897,  0.6734,  0.4039,  0.1909, -0.6221],
         [-1.8639, -2.5551, -1.8447, -0.2174, -0.1130],
         [ 1.5667,  2.4276, -1.8247, -0.2462,  0.0605],
         [-0.0302,  0.4692,  0.2567, -1.3758,  1.2917]]])