- date: 2021-08-12 10:17:17
- author: Jerry Su
- slug: Numpy-np.where
- title: Numpy np.where
- category: 
- tags: Numpy

[TOC]

In [2]:
import numpy as np

In [37]:
scores = -1 + 2 * np.random.random(size=(2, 4, 4)) #  随机生成[-1, 1]之间小数
scores

array([[[ 0.75522985,  0.75705722, -0.36925089,  0.86620857],
        [-0.4174211 , -0.36308435,  0.98568016, -0.44886813],
        [ 0.28443286,  0.71100813,  0.79377422,  0.96208261],
        [ 0.79448971, -0.39912178,  0.72051454,  0.24923677]],

       [[-0.66092566,  0.76876289,  0.50473514,  0.18878562],
        [ 0.1041725 ,  0.92939518,  0.72846323,  0.15859054],
        [-0.56339527,  0.02153888, -0.76440716, -0.73993331],
        [ 0.45476065, -0.75519827,  0.90017872, -0.45515793]]])

In [38]:
locs = np.where(scores > 0.5)
locs

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 1, 2, 2, 2, 3, 3, 0, 0, 1, 1, 3]),
 array([0, 1, 3, 2, 1, 2, 3, 0, 2, 1, 2, 1, 2, 2]))

In [39]:
for dim0, dim1, dim2 in zip(*locs):
    print(dim0, dim1, dim2)

0 0 0
0 0 1
0 0 3
0 1 2
0 2 1
0 2 2
0 2 3
0 3 0
0 3 2
1 0 1
1 0 2
1 1 1
1 1 2
1 3 2
