date: 2021-01-04 11:17:17
author: Jerry Su
slug: torch.nn.CrossEntropyLoss
title: torch.nn.CrossEntropyLoss
category: 
tags: Deep Learning, Pytorch
summary: Reason is the light and the light of life.
toc: show

[https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss)

In [18]:
import torch
from torch.nn import CrossEntropyLoss

BATCH_SIZE = 2
MAX_SEQ_LENGTH = 3
EMBEDDING_SIZE = VOCAB_SIZE = 5

In [19]:
input_ids = torch.randn((BATCH_SIZE, MAX_SEQ_LENGTH, EMBEDDING_SIZE))
input_ids

tensor([[[-1.2207e-01,  9.4908e-01,  9.6387e-02,  1.4286e+00,  1.9476e+00],
         [ 6.7663e-01,  8.2334e-04, -2.6130e+00,  3.3753e-02, -3.8190e-01],
         [-2.3500e-01,  1.7386e-01, -9.2278e-01,  6.7210e-01, -5.9908e-01]],

        [[-7.6696e-01,  1.0766e+00, -3.9904e-01,  1.3112e-01,  1.4053e-02],
         [ 1.1152e+00,  1.4323e+00,  8.4845e-01,  8.5321e-01, -2.1357e-01],
         [ 5.5852e-01,  1.7036e-01,  4.6033e-01,  1.2075e+00, -9.5198e-01]]])

In [21]:
labels = torch.randint(low=0, high=4, size=(BATCH_SIZE, MAX_SEQ_LENGTH))
labels

tensor([[2, 0, 2],
        [2, 0, 3]])

In [22]:
loss_fct = CrossEntropyLoss()

In [28]:
"""
 - Input: :math:`(N, C)` where `C = number of classes`, or
          :math:`(N, C, d_1, d_2, ..., d_K)` with :math:`K \geq 1`
          in the case of `K`-dimensional loss.
        - Target: :math:`(N)` where each value is :math:`0 \leq \text{targets}[i] \leq C-1`, or
          :math:`(N, d_1, d_2, ..., d_K)` with :math:`K \geq 1` in the case of
"""
# 注意：input是一个隐向量，loss_fct内回自动算arg_max，label是class整型值
loss_fct(input=input_ids.view(-1, EMBEDDING_SIZE), target=labels.view(-1))

tensor(1.7686)

In [36]:
# EMBEDDING_SIZE即CLASS类别数，即字典大小VOCAB_SIZE。注意label值要与EMBEDDING_SIZE一致
labels = torch.randint(low=0, high=10, size=(BATCH_SIZE, MAX_SEQ_LENGTH))
labels

tensor([[6, 2, 5],
        [7, 7, 1]])

In [37]:
# 越界
loss_fct(input=input_ids.view(-1, EMBEDDING_SIZE), target=labels.view(-1))

IndexError: Target 6 is out of bounds.