- date: 2021-02-15 10:17:17
- author: Jerry Su
- slug: Viterbi-Algorithm
- title: Viterbi Algorithm
- category: 
- tags: Viterbi, Algorithm

## 矩阵法

注：转移矩阵和发射矩阵以列维度上形式表示概率分布的，即列维度axis=1上元素和为1。**注意：把隐状态概率分布表示为向量后，向量乘以状态转移矩阵的结果为新的隐状态。** 同理，对发射矩阵做向量矩阵乘法会得到新的观测状态。

In [22]:
import numpy as np
from typing import List, Optional, Tuple

In [ ]:
def step(score_prev: np.ndarray,
         emission_probs: np.ndarray,
         transition_probs: np.ndarray,
         observed_state: int) -> Tuple[np.ndarray, np.ndarray]:
    """Runs one step of the Viterbi algorithm.
    
    Args:
        score_prev: probability distribution with shape (num_hidden),
            the previous score
        emission_probs: the emission probability matrix (num_hidden,
            num_observed)
        transition_probs: the transition probability matrix, with
            shape (num_hidden, num_hidden)
        observed_state: the observed state at the current step
    
    Returns:
        - the score for the next step
        - the maximizing previous state, before the current state, as an int array with shape (num_hidden)
    """
    

def viterbi(emission_probs: np.ndarray,
            transaction_probs: np.array,
            start_probs: np.ndarray,
            observed_states: List[int]) -> Tuple[List[int], float]:
    """运行维特比算法获得最有可能的状态序列。
    
    Args:
        emission_probs:
        transaction_probs:
        start_probs:
        observed_states:
        
    Returns:
        - 最有可能的状态序列。
        - 状态和观测序列的联合概率值。
    """
    # 运行正向传递，存储最有可能的先前状态。
    score = start_probs * emission_probs[:, observed_states[0]]  # 第一个时间步的最优解向量（隐含状态向量维度）
    all_pre_states = []
    for observed_state in observed_states[1:]:
        score, prevs = step(score, emission_probs, transaction_probs, observed_state)
        all_pre_states.append(prevs)

In [2]:
num_hidden_states = 3     # vocab_size
num_observed_states = 2   # vocab_size
num_time_steps = 4        # sequence_length

In [23]:
# 初始化转移概率矩阵
transaction_probs = np.array([
    [0.1, 0.2, 0.7],
    [0.1, 0.1, 0.8],
    [0.5, 0.4, 0.1],
])
assert transaction_probs.shape == (num_hidden_states, num_hidden_states)
assert transaction_probs.sum(axis=1).mean() == 1.0

# 初始化发射概率矩阵 （行 -> 隐含状态：0，1，2，列 -> 观测状态：0，1）
emission_probs = np.array([
    [0.1, 0.9],
    [0.3, 0.7],
    [0.5, 0.5],    
])
assert emission_probs.shape == (num_hidden_states, num_observed_states)
assert emission_probs.sum(axis=1).mean() == 1.0

# 初始隐状态概率
init_hidden_state_probs = np.array([0.1, 0.3, 0.6])
assert init_hidden_state_probs.shape == (num_hidden_states,)

# 定义观测序列
observed_states = [1, 1, 0, 1]
assert len(observed_states) == num_time_steps

In [24]:
init_hidden_state_probs

array([0.1, 0.3, 0.6])

In [29]:
emission_probs

array([[0.1, 0.9],
       [0.3, 0.7],
       [0.5, 0.5]])

In [30]:
score = init_hidden_state_probs * emission_probs[:, 0]
score

array([0.01, 0.09, 0.3 ])

In [44]:
transaction_probs.T

array([[0.1, 0.1, 0.5],
       [0.2, 0.1, 0.4],
       [0.7, 0.8, 0.1]])

In [46]:
pre_max = score * transaction_probs.T
pre_max

array([[0.001, 0.009, 0.15 ],
       [0.002, 0.009, 0.12 ],
       [0.007, 0.072, 0.03 ]])

In [47]:
np.argmax(pre_max, axis=1)

array([2, 2, 1])