In [ ]:
- date: 2020-11-21 10:17:17
- author: Jerry Su
- slug: cmrc2018-dataset
- title: cmrc2018 dataset
- category: 
- tags: Deep Learning, TensorFlow

In [22]:
!pip install datasets

In [23]:
from datasets import list_datasets

In [24]:
datasets_list = list_datasets()
len(datasets_list)

179

In [25]:
datasets = [dataset for dataset in datasets_list]
', '.join(datasets)

'Fraser/news-category-dataset, aeslc, ag_news, ai2_arc, allocine, amazon_us_reviews, anli, arcd, art, aslg_pc12, asnq, billsum, biomrc, blended_skill_talk, blimp, blog_authorship_corpus, bookcorpus, bookcorpusopen, boolq, break_data, c4, cdminix/mgb1, cfq, civil_comments, clue, cmrc2018, cnn_dailymail, coarse_discourse, com_qa, common_gen, commonsense_qa, compguesswhat, conll2000, conll2003, coqa, cornell_movie_dialog, cos_e, cosmos_qa, crd3, crime_and_punish, csv, daily_dialog, definite_pronoun_resolution, discofuse, docred, doqa, drop, eli5, emo, emotion, empathetic_dialogues, eraser_multi_rc, esnli, event2Mind, fever, flores, fquad, gap, germeval_14, gigaword, glue, guardian_authorship, hans, hansards, hellaswag, hotpot_qa, hyperpartisan_news_detection, imdb, iwslt2017, jeopardy, joelito/sem_eval_2010_task_8, json, kilt_tasks, kilt_wikipedia, kor_nli, lc_quad, lhoestq/squad, librispeech_lm, lince, lm1b, math_dataset, math_qa, matinf, mlqa, mlsum, movie_rationales, ms_marco, multi_ne

In [26]:
from datasets import load_dataset

In [27]:
train_cmrc, test_cmrc = load_dataset('cmrc2018',cache_dir='./' , split=['train', 'test'])

Using custom data configuration default
Reusing dataset cmrc2018 (./cmrc2018/default/0.1.0/c7b7e6267a94990b52713c35eb1ba91c18265524d7fe7317a85e6e1b1b85cc8f)


In [28]:
print(train_cmrc)

Dataset(features: {'id': Value(dtype='string', id=None), 'context': Value(dtype='string', id=None), 'question': Value(dtype='string', id=None), 'answers': Sequence(feature={'text': Value(dtype='string', id=None), 'answer_start': Value(dtype='int32', id=None)}, length=-1, id=None)}, num_rows: 10142)


In [40]:
x = 500
train_cmrc[x:x+10]

{'answers': [{'answer_start': [122], 'text': ['JR东日本所属的月台区是位于车站二楼']},
  {'answer_start': [369], 'text': ['1998年3月29日由地面车站改建为高架车站。']},
  {'answer_start': [10], 'text': ['日本长野县上田市天神1丁目']},
  {'answer_start': [166], 'text': ['检票口皆位于二楼的桥上站屋内']},
  {'answer_start': [158],
   'text': ['凤凰卫视资讯台会在每晚20点档《凤凰正点播报》开始前播放国歌，播放版本与香港电视台主流频道一致']},
  {'answer_start': [108], 'text': ['凤凰卫视资讯台于2013年开播高清版，此时标清版为切边播出。']},
  {'answer_start': [356],
   'text': ['该服务一般提供给中国境内三星级或以上的涉外宾馆酒店、外国人居住区、领事馆及大使馆。']},
  {'answer_start': [336], 'text': ['繁殖期约为7月至翌年2月']},
  {'answer_start': [375], 'text': ['半领彩鹬是在智利及阿根廷等地是民间传统上的赛鸟，因此多有被捕猎的纪录。']},
  {'answer_start': [447],
   'text': ['但到目前为止，仍未有文献指其种群数目有太大的威胁，因此在IUCN红色名录内评为无危物种。']}],
 'context': ['上田车站（）是一位于日本长野县上田市天神1丁目，由东日本旅客铁道（JR东日本）、信浓铁道（）与上田电铁所共用的铁路车站。上田车站是JR东日本所经营的北陆新干线与两条地方铁路线信浓铁道线（）与上田电铁别所线之交会车站。配合全面高架化的新干线路线，JR东日本所属的月台区是位于车站二楼（但检票口位于一楼），至于信浓铁道与上田电铁的部分，检票口皆位于二楼的桥上站屋内，但月台与铁路线则分别设置于二楼（信浓铁道线）与一楼（别所线）处。对向式月台2面2线的高架车站。。是北陆新干线轻井泽至长野段唯一的高架车站。由于不设待避线，因此设有月台闸门。起初计划为岛式2面4线，

In [13]:
from transformers import BertTokenizer

In [14]:
tokenizer = BertTokenizer.from_pretrained('hfl/chinese-bert-wwm-ext') #, do_lower_case=True)

In [20]:
inputs = tokenizer(text=train_cmrc[2]['question'],
                   text_pair=train_cmrc[2]['context'],
                   truncation='only_second',
                   padding='max_length',
                   max_length=100,
                   return_tensors='tf')
#inputs['start_position'] = train_cmrc[2]['answers']['answer_start'][0]
#inputs['end_position'] = inputs['start_position'] + len(train_cmrc[2]['answers']['text'][0]) - 1
inputs

{'input_ids': <tf.Tensor: shape=(1, 100), dtype=int32, numpy=
array([[ 101, 5745, 2455, 7563, 3221,  754,  862, 3198,  862, 1765, 1139,
        4495, 4638, 8043,  102, 5745, 2455, 7563, 3364, 3322, 8020, 8024,
        8021, 8024, 1760, 1399,  924, 4882,  185, 5735, 4449, 8020, 8021,
        8024, 3221, 6632, 1298, 5384, 7716, 1921,  712, 3136, 3364, 3322,
         511, 9155, 2399, 6158,  818,  711,  712, 3136, 8039, 8431, 2399,
        6158, 3091, 1285,  711, 1921,  712, 3136, 3777, 1079, 2600, 3136,
        1277, 2134, 2429, 5392, 4415, 8039, 8447, 2399, 6158, 3091, 1285,
         711, 2600,  712, 3136, 8024, 1398, 2399, 2399, 2419, 6158, 3091,
        1285,  711, 3364, 3322, 8039, 8170, 2399,  123, 3299, 4895,  686,
         102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 100), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1

In [68]:
def encode(instance):
    inputs_dict = tokenizer(text=instance['question'],
                            text_pair=instance['context'],
                            truncation='only_second',
                            padding='max_length',
                            max_length=512)
    inputs_dict['start_position'] = instance['answers']['answer_start'][0]
    inputs_dict['end_position'] = inputs_dict['start_position'] + len(instance['answers']['text'][0]) - 1
    return inputs_dict

In [69]:
train = train_cmrc.map(encode)
test = test_cmrc.map(encode)

In [70]:
print(len(train), len(test))

10142 1002


In [72]:
import torch

In [73]:
train.set_format(type='torch', columns=['input_ids', 'token_type_ids', 'attention_mask', 'start_position', 'end_position'])

In [75]:
dataloader = torch.utils.data.DataLoader(train, batch_size=32)

In [76]:
next(iter(dataloader))

/pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


{'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'end_position': tensor([ 34,  61, 125, 597, 779,  41, 253, 725, 204,  86, 195, 460,  44,  95,
         125, 221, 369,  69,  90, 193, 435, 498,  13, 134, 287, 227, 247, 335,
          17,  61,  22,  30]),
 'input_ids': tensor([[ 101, 5745, 2455,  ..., 2429, 5392,  102],
         [ 101, 8431, 2399,  ..., 4415,  809,  102],
         [ 101, 5745, 2455,  ..., 4415,  809,  102],
         ...,
         [ 101, 7942, 4324,  ...,    0,    0,    0],
         [ 101,  784,  720,  ...,    0,    0,    0],
         [ 101, 1762, 4179,  ...,    0,    0,    0]]),
 'start_position': tensor([ 30,  41,  97, 548, 759,  26, 247, 706, 202,  84, 156, 391,  27,  88,
         108, 213, 267,  61,  86, 185, 397, 463,  11, 126, 237, 150, 229, 320,
           0,  57,   0,  23]