- date: 2021-01-14 11:17:17
- author: Jerry Su
- slug: torch.lt/torch.gt/torch.le/torch.ge/torch.ne
- title: torch.lt/torch.gt/torch.le/torch.ge/torch.ne
- category: 
- tags: Deep Learning, Pytorch

[https://pytorch.org/docs/stable/torch.html#comparison-ops](https://pytorch.org/docs/stable/torch.html#comparison-ops)

In [1]:
import torch

In [11]:
a = torch.randint(0, 10, [5])
b = torch.randint(0, 10, [5])
print(a)
print(b)

tensor([9, 0, 9, 2, 4])
tensor([7, 8, 5, 3, 6])


In [12]:
a.lt(b)         # <

tensor([False,  True, False,  True,  True])

In [13]:
torch.le(a, b) # <=

tensor([False,  True, False,  True,  True])

In [14]:
a.gt(b)        # >

tensor([ True, False,  True, False, False])

In [15]:
a.ge(b)        # >=

tensor([ True, False,  True, False, False])

In [18]:
a.ne(b)       # !=

tensor([True, True, True, True, True])

In [27]:
a.ge(b).all()

tensor(False)

In [39]:
torch.arange(10, 5)

RuntimeError: upper bound and larger bound inconsistent with step sign

In [40]:
a

tensor([9, 0, 9, 2, 4])

In [51]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([3,2,3,4,5])

In [53]:
for s,e in zip(a, b):
    print(a)
    print(a[s:e])
    break

tensor([1, 2, 3, 4, 5])
tensor([2, 3])
