- date: 2022-05-04 11:17:17
- author: Jerry Su
- slug: Pytorch-stride-as_strided
- title: Pytorch tensor.stride & tensor.as_strided
- category: 
- tags: Pytorch

## tensor.stride()

任意维度上的步长，是其低维度乘积。

shape: (12, 512, 768) stride: (512*768*1, 768*1, 1*1)

## tensor.as_strided()

- input (Tensor) – the input tensor.

- size (tuple or ints) – the shape of the output tensor

- stride (tuple or ints) – the stride of the output tensor

- storage_offset (int, optional) – the offset in the underlying storage of the output tensor

由input张量，以指定的size, stride, storage_offset创建新的view。

In [2]:
import torch

In [46]:
x = torch.randn(3, 2, 4)
x

tensor([[[ 0.9071,  0.2834, -0.1989, -1.4063],
         [-1.7204,  1.7097, -1.2490,  1.1157]],

        [[ 1.7791,  0.6694,  0.3891, -0.0156],
         [-1.6843, -1.1728,  0.0408, -0.7561]],

        [[ 0.9002,  1.4651,  0.7972,  1.1046],
         [ 1.4144,  0.3738,  0.4680,  0.9603]]])

In [77]:
print(f"0维度上的步长：{len(x[0]) * len(x[0][0] * 1)}\n"
      f"1维度上的步长：{len(x[0][0]) * 1}\n"
      f"2维度上的步长：{1 * 1}")

x.stride()

0维度上的步长：8
1维度上的步长：4
2维度上的步长：1


(8, 4, 1)

In [78]:
x[0]

tensor([[ 0.9071,  0.2834, -0.1989, -1.4063],
        [-1.7204,  1.7097, -1.2490,  1.1157]])

In [67]:
x[0][0]

tensor([ 0.9071,  0.2834, -0.1989, -1.4063])

In [59]:
x[0][0][0]

tensor(0.9071)

In [61]:
x.shape

torch.Size([3, 2, 4])

In [81]:
x1 = torch.randn(5, 20, 10) # stride: (20 * 10 * 1, 10 * 1, 1 * 1)
x1.stride()

(200, 10, 1)

In [75]:
x2 = torch.randn(10, 15, 256, 64) # stride: (15 * 256 * 64 * 1, 256 * 64 * 1, 64 * 1, 1 *1)
print((15 * 256 * 64 * 1, 256 * 64 * 1, 64 * 1, 1 *1))
x2.stride()

(245760, 16384, 64, 1)


(245760, 16384, 64, 1)