- date: 2021-01-07 12:17:17
- author: Jerry Su
- slug: pytorch-create-tensor
- title: Pytorch-create-tensor
- category: 
- tags: Deep Learning, Pytorch

In [1]:
import torch

In [9]:
torch.zeros([4, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones([4, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.empty([2, 3]) # 未初始化

tensor([[-3.1336e-15,  4.5867e-41,  3.8922e-17],
        [ 3.0684e-41,  4.4842e-44,  0.0000e+00]])

In [13]:
torch.full([2, 3], 0.5)  # 常用于初始化概率值

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])